### PR TITLE
my_side_of_the_story

### PR DESCRIPTION
**Pull request by jesgum**

### CODE REVIEW

**Comment by floridop** [comment]
Hi! Thanks for your submission.

Unfortunately it seems that there were changes in the main that conflict with yours. 
Could you please perform a merge as described in Tutorial 5 slides 82-96 and integrate those changes?
Start with synchronizing your local main with my upstream main as described in slide 86.
We do not want to lose any existing content, so you should keep what others have written and add yours.
You're free to reorganize the content blocks so that it still makes a story, but please do minimal changes
to the content of what others have written to integrate them with yours.
You have time until the 20th of October at 19:00. 
If you can't make it by that time or you are done before the deadline, 
please add a comment in github so that I can progress with another student.

**Comment by jesgum** [comment]
Hi! I think I should be done now.

**Comment by jesgum** [comment]
Alright! I've added what I previously deleted! And I kept the monkey :)

**Comment by floridop** [comment]
Looks very good now! thanks!

**Pull request merged**
