### PR TITLE
My side of the story.

### PR DESCRIPTION
**Pull request by udi251nikolei**
I've introduced new character to the fairytale. My submission directly follows line 21.

### CODE REVIEW

**Comment by floridop** [comment]
Hi! Thanks for your submission.

Unfortunately it seems that there were changes in the main that conflict with yours. 
Could you please perform a merge as described in Tutorial 5 slides 82-96 and integrate those changes?
Start with synchronizing your local main with my upstream main as described in slide 86.
We do not want to lose any existing content, so you should keep what others have written and add yours.
You're free to reorganize the content blocks so that it still makes a story, but please do minimal changes
to the content of what others have written to integrate them with yours. 
You have time until the 21th of October at 16:00. 
If you can't make it by that time or you are done before the deadline, 
please add a comment in github so that I can progress with another student.

**Comment by udi251nikolei** [comment]
I have integrate my part of the story, fixed the conflict and updated my pull request.

**Comment by floridop** [comment]
Sad that the boss character disappeared, but we're running out if time so I'll accept this, looks very good. Thanks!

**Comment by floridop** [comment]
Thanks for your contribution! Scenario A completed! See canvas for results

**Pull request merged**
