### PR TITLE
My side story

### PR DESCRIPTION
**Pull request by chlee295**

### CODE REVIEW

**Comment by chlee295** [comment]
I think I have merged again by following the slides you mention. I am wondering if I do it correctly.

**Comment by floridop** [comment]
Hi @chlee295 ,

I think you are initiating the merge correctly but you're not completing it properly. You need to delete the lines containing `<<<<<<< HEAD` , `======` and `>>>>>`  and decide what you want to keep of the text contained in between these lines, eventually following my comment https://github.com/floridop/MNXB01-fairytale/pull/67#pullrequestreview-1154436287.

I suggest you wait until the 26th of October before going further. The text will change again by that time. 

Let me try to clarify:

**Comment by floridop** [comment]
I tried to update my comments with more details, I hope it helps.

**Comment by chlee295** [comment]
I have deleted some special lines according to your comments.

**Comment by floridop** [comment]
Good job!
Thanks for your contribution! Scenario A completed! See canvas for results

**Pull request merged**
